os: linux
language: r # this image includes also node 6
r_packages:
  - lattice
before_install:
  - Rscript --version
script:
  - echo "Cloning hopkins repos..."
  - mkdir -p input
  - git clone https://github.com/CSSEGISandData/COVID-19.git input/hopkins
  - echo "Cloning gh-pages branch..."
  - git clone -b gh-pages --single-branch https://github.com/insysbio/covid-19-data output
  - cp -f README.md output/README.md
  - echo "Starting hopkins data transformation..."
  - mkdir -p r_libs
  - Rscript.exe ./R/transform-hopkins-data.R
after_success:
  - echo "Sending files to gh-pages branch..."
