os: linux
language: r # this image includes also node 6
r_packages:
  - tidyr
  - dplyr
  - jsonlite
  - ISOcodes
before_install:
  - Rscript --version
install:
  - echo "Cloning hopkins repos..."
  - mkdir -p input
  - git clone https://github.com/CSSEGISandData/COVID-19.git input/hopkins
  - ls input/hopkins
script:
  - echo "Cloning gh-pages branch..."
  - git clone -b gh-pages --single-branch https://github.com/insysbio/covid-19-data output
  - cp -f README.md output/README.md
  - cp -f LICENSE output/LICENSE.md
  - echo "Starting hopkins data transformation..."
  - mkdir -p r_libs
  - Rscript ./R/start.R
  - mkdir -p 'output/hopkins/source'
  - cp -f input/hopkins/csse_covid_19_data/csse_covid_19_time_series/*.csv 'output/hopkins/source/'
after_success:
  - echo "Sending files to gh-pages branch..."
  - cd output
  - git config user.name travis_runner
  - git config user.email "notexist@insysbio.com"
  - git add --all
  - git commit -m "created based on commit $TRAVIS_BUILD_NUMBER"
  - git push https://${GH_TOKEN}@github.com/insysbio/covid-19-data HEAD:gh-pages
branches:
  only:
  - master
cache:
  R: true
